<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJZ9OLFG\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJZ9OLFG/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerJZ9OLFG.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerJZ9OLFG\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerJZ9OLFG\appAppKernelProdContainer([
    'container.build_hash' => 'JZ9OLFG',
    'container.build_id' => '678f3d88',
    'container.build_time' => 1710596378,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJZ9OLFG');
