<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMNLdPCX\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMNLdPCX/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerMNLdPCX.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerMNLdPCX\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerMNLdPCX\appAppKernelProdContainer([
    'container.build_hash' => 'MNLdPCX',
    'container.build_id' => 'd9187706',
    'container.build_time' => 1709712572,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMNLdPCX');
