version: '3'
services:
  web:
    build: apache
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/app
      - ./apache/exemplo.lan.conf:/etc/apache2/sites-enabled/exemplo.lan.conf
      - ./apache/${CERT_FILE}:/etc/ssl/certs/${CERT_FILE}
      - ./apache/${KEY_FILE}:/etc/ssl/private/${KEY_FILE}

volumes:
  datos:
