<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNxKpcWG\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNxKpcWG/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerNxKpcWG.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerNxKpcWG\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerNxKpcWG\appAppKernelProdContainer([
    'container.build_hash' => 'NxKpcWG',
    'container.build_id' => '73cbc7c0',
    'container.build_time' => 1709904496,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNxKpcWG');
